---
title: "writeup"
author: "Rafael Cruz Gil"
date: "3 June 2018"
output: html_document
---

### Project Explanation

This project was meant to serve as an unofficial companion for my thesis, a way to present information that is on it that can’t be accessed on paper. My thesis is about trade routes in Galilee during the Late Hellenistic and Early Roman periods. I show that sites on the eastern shore of the Sea of Galilee had a greater connectivity than those on the western one and that, thus, a tradition of archaeological and historical literature on the subject is mistaken. To do this I used historiographical analysis, pottery distribution, and numismatic finds. Of these types of data, only the latter lent itself to producing graphs and maps, so it was the one chosen for the visualisations. In order to fulfil its purpose of complementing the written thesis, interactive elements were used. For example, instead of tables, graphs that use plotly and tell the same information while hovering over them were produced.
Creating this project was more challenging than I expected for many reasons. I was forced to revise and explore options for the visualisations and had to give up on the last category, one that is probably the most important to me.
The first tab, which centres on the coins found in five Galilean sites and their provenance, was simple enough, and with feedback I was able to improve the second column, which went from presenting a single bar, stacked for cultural groups within a city, to a bar for each group. This did make it much clearer and helped provide a baseline for comparison.

The data is truthful, compiled through scraping archaeological reports, and is centred in the chosen period with no gaps. While a larger sample of sites would have been useful, I utilised the information available to me and I acknowledge its limitations (Gamla has a much larger number of coins than any of the other sites, for example). As for its functionality, I chose a stacked bar chart because it allowed to compare general proportions between sites rapidly (a first graph includes coins of uncertain origin, the second one eliminates them). The second column focus on each individual site (with a tab assigned to each) and uses the number of coins, instead of proportion. It has the disadvantage, in the case of Gamla, that there are some groups with a very small number when compared to the most numerous ones that are barely visible without zooming in, but I did not know how to work around that. As for its beauty, it is not a particularly innovative or original way of presenting information, but I would argue it is an effective way. The insightfulness of this section (of the whole visualisation, to be fair) is probably trivial to anyone who is not an archaeologist. To those of us interested in the topic and area, it allows to glimpse the importance of Phoenician mints for settlements of all sizes in the area, for example (I was surprised by this while writing my thesis), while highlighting that the one site that did not have a predominantly Jewish population (Hippos) had a rather different distribution than the rest. As for it being enlightening, it does not have real-world stakes of any kind.

The second and third tabs were originally meant to be a single one that would have looked very different. I intended to have an upper row divided in two, with a 2d network visualisation on one half and a 3d one on the other, and a lower row with tabs for the network of mints for each site. However, the 3d visualisation, while beautiful, did not add any insight and was difficult to interpret, so I dropped it. Then, I realised that the networks for each site were redundant; the interactive 2d visualisation was capable of presenting the same information in a more complete and effective way. My attempts to let the visualisation switch between showing whether each city was a site were found, a mint, or both, and the culture to which each site was linked failed; attempting to set different categories to the visualisation caused it to stop rendering. I was therefore forced to add a second visualisation which highlighted that category, for which I had to create a new csv file. I then presented one visualisation on top of the other. This, however, meant that viewing each one in a row format made them too small to be viewed comfortably. I then compared viewing them in separate tabs versus viewing in them columns one next to the other. I chose the latter option.

The visualisations, as before, are truthful, probably of little interest to anyone outside archaeology, and do not have real-world stakes. As for their beauty and functionality, I argue that they are effective at presenting the information and that their interactivity makes them interesting.

The third part of the project was meant to be an interactive map that showed all sites mentioned and, when hovering over each site, would tell whether it was a mint, a site, or both, the number of coins found and/or minted, its name, and to which culture it was associated. However, I was unable to get my csv file with coordinates and site information to deploy correctly while converting it to a .shp file. I had to give up due to a lack of time and used instead jpg images produced with ESRI’s ArcGIS. The lack of interactivity meant that two different maps were needed, one that showed the full range of the location of the mints, which goes from Italy to Iran, and another one that zoomed in on the Levant and showed an area too cluttered to be labelled on the larger scale one. Since one map was portrait oriented and the other one landscape oriented, two separate tabs were used. This section was the one that I cared the most about, since I am trying to leave ArcGIS for free software, and the one on which I was unable to present anything done by myself using code (apart from the pre-set Python scripts for ArcMap). The lack of interactivity is a huge hindrance, since this the one place where the information presented is in the same format as in the written thesis and does not offer anything new. It is, however, truthful, and it properly shows that for five sites in a small Roman province the range of numismatic findings is wide.

All in all, the project does not offer information that is likely to have much of an impact in the modern world. However, I do believe that it fulfils its role of complementing my written thesis and presenting information from it in a way that would be impossible to do in paper (apart from the maps section). Creating this was challenging and fun (although frustrating at times) and I hope to be able to advance further on these techniques —and to soon be able to actually create an interactive map using R.

